M48
; DRILL file KiCad 10.0.3 date 2026-06-13T13:31:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-13T13:31:21+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X130.81Y-77.216
X130.81Y-106.172
X176.0Y-77.2
X176.022Y-106.299
M30
